### ISSUE TITLE
missing features?

### ISSUE THREAD

**Issue by emmanueltouzery** [saneyuki/option-t.js#158]
I miss a couple of features in the library:

1. `Option<T>.contains(T): boolean`
2. Option<T>.unwrapOr(T) could be changed to `Option<T>.unwrapOr(T|null)` to make it easier to integrate with legacy code expecting null. Maybe could even be expanded to unwrapOr(T|null|undefined). Or we add Option<T>.orNull():T|null
3. `Option<T>.fromNullable(T|null|undefined)` (if T, you get Some, otherwise you get None). I see you use `new`, so maybe `new Option` as opposed to `new Some` or `new None`

EDIT: i've now found https://github.com/cwmyers/monet.js -- pretty interesting.

**Comment by saneyuki** [comment]
@emmanueltouzery 

Thank you for your proposal. I agree this operation is common operation. We may implement this as static function for the future.

However, basically, this project follows APIs which inspired by [Rust's `std::option`](https://doc.rust-lang.org/std/option/), and it's very low priority to implement APIs which Rust's one does not implement.

And implementing a new API increases our file size. It would be a problem as the library providing base primitive. So we don't like to implement them without the concrete reasons which proves a new API is useful.

Your proposed ones can be replaces these codes:

--------------------------

> 1. Option<T>.contains(T): boolean

```typescript
// `v instanceof TConstructor` could not checking for primitive types (e.g. `string`, `number`, or `boolean`),
// So we should take the function to checking it.
function containInOption<T>(option: Option<T>, fn: (v: T) => boolean):  boolean {
    return option.map(fn).unwrapOr(false);
}
```
--------------------------

> 2. Option.unwrapOr(T) could be changed to Option<T>.unwrapOr(T|null) to make it easier to integrate with legacy code expecting null.

```typescript
function unwrapOrUndefined<T>(option: Option<T>): T | undefined {
  let result: T | undefined = option.isSome ? option.unwrap() : undefined;
  return result;
}

function unwrapOrNull<T>(option: Option<T>): T | null {
  let result: T | null = option.isSome ? option.unwrap() : null;
  return result;
}
```

--------------------------

> 3. Option<T>.fromNullable(T|null|undefined)

```typescript
function fromNullable<T>(v: T | null | undefined): Option<T> {
    return (v === undefined || v === null) ? new None<T>() : new Some<T>(v);
}
```

> so maybe new Option as opposed to new Some or new None

The early version of this project had such APIs. But we obsolete it ( https://github.com/saneyuki/option-t.js/issues/17 ). In JavaScript world, there are some style to represent "null". So we decide that we should provide an explicit operation for interoperability with other style.
